error: rename panic_to_error as element_panic_to_error
This is to make it clear that it targets a specific type of `imp`, which is
different than `pad_panic_to_error`.

Part-of: <https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/2009>